language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly
    - php: 7.0

install:
  - composer update

script:
  - vendor/bin/phpcs --config-set installed_paths "../../wp-coding-standards/wpcs/,../../automattic/phpcs-neutron-standard/,../../inpsyde/php-coding-standards/,../../wimg/php-compatibility/,../../pheromone/phpcs-security-audit/Security/"
  - vendor/bin/phpcs -n
  - vendor/bin/phpunit

