language: php

php:
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env:
        - COVERAGE="true"
        - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  allow_failures:
    - php: nightly
    - php: 7.0

install:
  - composer update

script:
#  - vendor/bin/phpcs --config-set installed_paths "../../wp-coding-standards/wpcs/,../../automattic/phpcs-neutron-standard/,../../inpsyde/php-coding-standards/,../../wimg/php-compatibility/,../../pheromone/phpcs-security-audit/Security/"
#  - vendor/bin/phpcs -n
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_script:
  - if [ -n "$COVERAGE" ]; then bash <(curl -s https://codecov.io/bash); fi
  - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.xml;

notifications:
  email: false
