language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - sh -e ./.travis.scripts/compile.sh

script:
  - vendor/bin/phpunit