name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Clear cache of Composer
      run: composer clear-cache
      
    - name: Update Composer.json and composer.lock
      run: composer update
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Run PHPUnit tests
    - name: PHPUnit tests
      uses: php-actions/phpunit@v1
      with:
        config: ./phpunit.xml.dist
